name: Sync and merge upstream repository with your current repository
description: Syncs and merges your current repository with the upstream repository. Fork of https://github.com/mheene/sync-upstream-repo.
author: Dabreadman

inputs:
  upstream_repo:
    description: repositories for sync, if multi, delimit by space
    required: true
  upstream_branch:
    description: Branch to merge from upstream (defaults to downstream branch)
    required: false
    default: "main"
  token:
    description: GitHub Bot token
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.token }}

branding:
  icon: "git-merge"
  color: "blue"
